apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-server
spec:
  selector:
    matchLabels:
      app: author-server
  replicas: 1
  template:
    metadata:
      labels:
        app: author-server
    spec:
      # Skywalking start
#      volumes:
#        - name: skywalking-agent
#          emptyDir: { }
#
#      initContainers:
#        - name: agent-container
#          image: apache/skywalking-java-agent:8.7.0-alpine
#          volumeMounts:
#            - name: skywalking-agent
#              mountPath: /agent
#          command: [ "/bin/sh" ]
#          args: [ "-c", "cp -R /skywalking/agent /agent/" ]
      # Skywalking end

      containers:
        - name: author-server
          image: "wisekingdavid/author-server:latest"
          imagePullPolicy: Always
          ports:
            - name: http-author
              containerPort: 8080
#          imagePullSecrets:
#            - name: image-secret

          # Skywalking start
#          volumeMounts:
#            - name: skywalking-agent
#              mountPath: /skywalking
#          env:
#            - name: JAVA_TOOL_OPTIONS
#              value: "-javaagent:/skywalking/agent/skywalking-agent.jar"
#            - name: SW_AGENT_NAME
#              value: "author-server"
#            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
#              value: "127.0.0.1:11800"
              # Skywalking end

          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: author-server-service
  namespace: default
spec:
#  type: LoadBalancer
#  type: NodePort
  selector:
    app: author-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-author
#      nodePort: 30003
    - name: https
      protocol: TCP
      port: 443
      targetPort: http-author
##      nodePort: 30012



---
#apiVersion: route.openshift.io/v1
#kind: Route
#metadata:
#  name: author-route
#spec:
#  tls:
#    termination: passthrough
#  host: author-server-service.demo-project.rahtiapp.fi
#  port:
#    targetPort: 8500
#  to:
#    kind: Service
#    name: author-server-service
#

---
#apiVersion: v1
#kind: Endpoints
#metadata:
#  name: author-server-service
#subsets:
#  - addresses:
#      - ip: 192.0.2.42
#    ports:
#      - port: author-server

---

#apiVersion: v1
#data:
#  .dockerconfigjson: >-
#    eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJkb2NoaWEyMSIsInBhc3N3b3JkIjoiUGFtZWxhZG9yaXMwODAiLCJlbWFpbCI6ImRvY2hpYTIxQHN0dWRlbnQub3VsdS5maSIsImF1dGgiOiJaRzlqYUdsaE1qRTZVR0Z0Wld4aFpHOXlhWE13T0RBPSJ9fX0=
#kind: Secret
#metadata:
#  creationTimestamp: '2022-08-02T06:40:34Z'
#  name: image-secret
#  namespace: demo-project
#  resourceVersion: '1569206684'
#  selfLink: /api/v1/namespaces/demo-project/secrets/image-secret
#  uid: 02b4f2f8-122e-11ed-8b9c-fa163e081ad5
#type: kubernetes.io/dockerconfigjson
